repos:
  - repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [pre-commit]
        language: system
        entry: |
          jupyter nbconvert
          --inplace
          --ClearOutputPreprocessor.enabled=True
          --ClearMetadataPreprocessor.enabled=True
          --ClearMetadataPreprocessor.preserve_nb_metadata_mask="kernelspec"
