[formats]
"notebooks/" = "ipynb"
"nhf_assist/notebooks/" = "ipynb"
"pestpp_ies_calibration/notebooks/" = "ipynb"
"notebook_scripts/" = "py:percent"
"nhf_assist/notebook_scripts/" = "py:percent"
"pestpp_ies_calibration/notebook_scripts/" = "py:percent"
"workflow_templates/nhm/" = "py:percent"
"workflow_templates/nhf/" = "py:percent"
"workflow_templates/pest/" = "py:percent"
