[formats]
"notebooks/" = "ipynb"
"nhf_assist/notebooks/" = "ipynb"
"pestpp_ies_calibration/notebooks/" = "ipynb"
"../src/workflow_templates/nhm/" = "py:percent"
"../src/workflow_templates/nhf/" = "py:percent"
"../src/workflow_templates/pest/" = "py:percent"
