"""Workspace bridge and service helpers for Pixi-driven workflows."""

from assist.workspace.bridge import (
    MODEL_SUBDIRS,
    REPO_NOTEBOOK_DIRS,
    WORKFLOW_NAMES,
    ensure_workspace_root,
    get_model_dir,
    get_model_workflow_notebooks_dir,
    get_project_active_model_config_path,
    get_project_config_dir,
    get_project_dir,
    get_project_models_dir,
    get_project_notebooks_dir,
    get_project_workflow_notebooks_dir,
    get_workflow_notebooks_dir,
    is_model_dir,
    is_project_dir,
    list_models,
    list_projects,
    resolve_project_notebook_context,
    resolve_repo_root,
    resolve_model_notebook_context,
    resolve_workspace_root,
)
from assist.workspace.examples import resolve_example_source
from assist.workspace.service import (
    bootstrap_workspace,
    copy_example_model,
    create_model,
    create_project,
    get_active_model_name,
    get_active_model_root,
    get_models,
    get_projects,
    import_model,
    prepare_model_runtime,
    set_active_model,
)

__all__ = [
    "MODEL_SUBDIRS",
    "REPO_NOTEBOOK_DIRS",
    "WORKFLOW_NAMES",
    "bootstrap_workspace",
    "copy_example_model",
    "create_model",
    "create_project",
    "ensure_workspace_root",
    "get_active_model_name",
    "get_active_model_root",
    "get_model_dir",
    "get_model_workflow_notebooks_dir",
    "get_models",
    "get_projects",
    "get_project_active_model_config_path",
    "get_project_config_dir",
    "get_project_dir",
    "get_project_models_dir",
    "get_project_notebooks_dir",
    "get_project_workflow_notebooks_dir",
    "get_workflow_notebooks_dir",
    "import_model",
    "is_model_dir",
    "is_project_dir",
    "list_models",
    "list_projects",
    "prepare_model_runtime",
    "resolve_example_source",
    "resolve_model_notebook_context",
    "resolve_project_notebook_context",
    "resolve_repo_root",
    "resolve_workspace_root",
    "set_active_model",
]
