"""Workspace bridge and service helpers for Pixi-driven workflows."""

from assist.workspace.bridge import (
    MODEL_SUBDIRS,
    WORKFLOW_NAMES,
    ensure_workspace_root,
    get_model_dir,
    get_project_active_model_config_path,
    get_project_config_dir,
    get_project_dir,
    get_project_models_dir,
    get_project_notebooks_dir,
    get_project_workflow_notebooks_dir,
    is_model_dir,
    is_project_dir,
    list_models,
    list_projects,
    resolve_project_notebook_context,
    resolve_repo_root,
    resolve_workspace_root,
)
from assist.workspace.examples import resolve_example_source
from assist.workspace.kernels import (
    DEFAULT_KERNEL_DISPLAY_NAME,
    DEFAULT_KERNEL_NAME,
    DEV_KERNEL_DISPLAY_NAME,
    DEV_KERNEL_NAME,
    PAIRING_MODE_KERNELS,
    ensure_kernel_registered,
    list_kernel_names,
)
from assist.workspace.service import (
    bootstrap_workspace,
    copy_example_model,
    create_model,
    create_project,
    get_active_model_name,
    get_active_model_root,
    get_models,
    get_projects,
    import_model,
    prepare_model_runtime,
    set_active_model,
)
from assist.workspace.setup import run_setup

__all__ = [
    "DEFAULT_KERNEL_DISPLAY_NAME",
    "DEFAULT_KERNEL_NAME",
    "DEV_KERNEL_DISPLAY_NAME",
    "DEV_KERNEL_NAME",
    "MODEL_SUBDIRS",
    "PAIRING_MODE_KERNELS",
    "WORKFLOW_NAMES",
    "bootstrap_workspace",
    "copy_example_model",
    "create_model",
    "create_project",
    "ensure_kernel_registered",
    "ensure_workspace_root",
    "get_active_model_name",
    "get_active_model_root",
    "get_model_dir",
    "get_models",
    "get_projects",
    "get_project_active_model_config_path",
    "get_project_config_dir",
    "get_project_dir",
    "get_project_models_dir",
    "get_project_notebooks_dir",
    "get_project_workflow_notebooks_dir",
    "import_model",
    "is_model_dir",
    "is_project_dir",
    "list_kernel_names",
    "list_models",
    "list_projects",
    "prepare_model_runtime",
    "resolve_example_source",
    "resolve_project_notebook_context",
    "resolve_repo_root",
    "resolve_workspace_root",
    "run_setup",
    "set_active_model",
]
