"""Compatibility shim. Implementation lives in assist.common.map_template.

Concern 4 of the helper unification. nhf's `map_template_v2` was the
dominant side -- 29 functions to nhm's 21, with zero nhm-only functions --
so it moved to `assist.common.map_template` in a bare `git mv` commit of
its own, which is why plain `git blame` still credits the original authors
there. The GFv1.1-only headwater-basin layers that nhf had commented out
(`HW_basins`, `HW_basins_gdf`, the `hw_id` HRU overlay) are restored in the
unified module as `None`-defaulted parameters with guarded rendering, so
nhm's notebooks keep their layers and GFv2 callers are unaffected.
"""
from assist.common.map_template import (
    create_FMI_poi_markers,
    create_annual_output_var_map,
    create_geology_map,
    create_hru_label,
    create_hru_map,
    create_minimap,
    create_nhru_par_map,
    create_non_poi_marker_cluster,
    create_non_poi_obs_marker_cluster,
    create_non_ref_gages_markers,
    create_poi_marker_cluster,
    create_poi_obs_marker_cluster,
    create_poi_paramplot_marker_cluster,
    create_ref_gages_markers,
    create_segment_map_hide,
    create_segment_map_show,
    create_streamflow_poi_markers,
    folium_map_elements,
    folium_map_tiles,
    is_wsl,
    make_geo_legend,
    make_geo_map,
    make_gf_map,
    make_hf_map,
    make_par_map,
    make_polygon_icon,
    make_streamflow_map,
    make_var_map,
    make_webbrowser_map,
    admin_basin_style,
    cal_style_function,
    hw_basin_style,
    popup_hru,
    popup_seg,
    tooltip_hru,
    tooltip_seg,
)

__all__ = [
    "create_FMI_poi_markers",
    "create_annual_output_var_map",
    "create_geology_map",
    "create_hru_label",
    "create_hru_map",
    "create_minimap",
    "create_nhru_par_map",
    "create_non_poi_marker_cluster",
    "create_non_poi_obs_marker_cluster",
    "create_non_ref_gages_markers",
    "create_poi_marker_cluster",
    "create_poi_obs_marker_cluster",
    "create_poi_paramplot_marker_cluster",
    "create_ref_gages_markers",
    "create_segment_map_hide",
    "create_segment_map_show",
    "create_streamflow_poi_markers",
    "folium_map_elements",
    "folium_map_tiles",
    "is_wsl",
    "make_geo_legend",
    "make_geo_map",
    "make_gf_map",
    "make_hf_map",
    "make_par_map",
    "make_polygon_icon",
    "make_streamflow_map",
    "make_var_map",
    "make_webbrowser_map",
    "admin_basin_style",
    "cal_style_function",
    "hw_basin_style",
    "popup_hru",
    "popup_seg",
    "tooltip_hru",
    "tooltip_seg",
]
