"""Compatibility shim. Implementation lives in assist.common.assist_utilities."""
from assist.common.assist_utilities import (
    bynhru_parameter_list,
    bynmonth_bynhru_parameter_list,
    bynsegment_parameter_list,
    create_append_gages_to_param_file,
    create_append_gages_to_param_file_v2,
    delete_notebook_output_files,
    fetch_FMI_npoigages_info,
    fetch_non_ref_npoigages_info,
    fetch_nwis_gage_info,
    fetch_ref_npoigages_info,
    fetch_waterdata_gage_info,
    find_missing_gage_info,
    load_subdomain_config,
    make_HW_cal_level_files,
    make_myparam_addl_gages_param_file,
    make_obs_plot_files,
    make_plots_par_vals,
)

__all__ = [
    "bynhru_parameter_list",
    "bynmonth_bynhru_parameter_list",
    "bynsegment_parameter_list",
    "create_append_gages_to_param_file",
    "create_append_gages_to_param_file_v2",
    "delete_notebook_output_files",
    "fetch_FMI_npoigages_info",
    "fetch_non_ref_npoigages_info",
    "fetch_nwis_gage_info",
    "fetch_ref_npoigages_info",
    "fetch_waterdata_gage_info",
    "find_missing_gage_info",
    "load_subdomain_config",
    "make_HW_cal_level_files",
    "make_myparam_addl_gages_param_file",
    "make_obs_plot_files",
    "make_plots_par_vals",
]
